"""initial schema

Revision ID: 1ec413cdf5e8
Revises: 
Create Date: 2026-07-21 11:46:31.918042

"""
from alembic import op
import sqlalchemy as sa


revision = '1ec413cdf5e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('styles', sa.String(length=300), nullable=True),
    sa.Column('country_base', sa.String(length=100), nullable=True),
    sa.Column('similarity', sa.String(length=300), nullable=True),
    sa.Column('gig_feed_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('festival', 'venue', 'jazz_club', 'bar', 'cultural_center', name='venuetype', native_enum=False, length=30), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'researched', 'draft_ready', 'sent', 'follow_up', 'confirmed', 'declined', 'not_a_fit', name='venuestatus', native_enum=False, length=30), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('booking_contact', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('application_method', sa.String(length=200), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('event_dates', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('last_contact', sa.Date(), nullable=True),
    sa.Column('next_action', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'sent', name='draftstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_artists',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_artists')
    op.drop_table('email_drafts')
    op.drop_table('venues')
    op.drop_table('artists')
    # ### end Alembic commands ###
